online_time_check_frequency: 20
join_permission: "arena.join"
kick_message: "Sei stato kicato"
insufficient_permissions: "Permessi insufficienti"
invalid_command_sender: "Questo comando è solo per player"
add_command_usage: "/patreon add <patreon> <player>"
add_command_success: "Patreon aggiunto con successo"
remove_command_usage: "/patreon remove <patreon> <player>"
remove_command_success: "Patreon rimosso con successo"
patreon_usage: "/patreon <remove:add:time> <player>"
patreon_not_found: "Nessun patreon trovato"
patreon_online_time: "%time"
