main: it.fireentity.patreon.access.PatreonAccess
name: PatreonAccess
version: 1.0-SNAPSHOT
authors: [Fireentity]
depend: [DataCore, arenaPermissions,FireLibrary]
commands:
  patreon:
    description: The main plugin command
